name: C/C++ CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: clone
      run: git clone https://github.com/fledge-iot/fledge; cd fledge; sudo ./requirements.sh; make; pwd
    - name: make
      run: mkdir -p build; cd build; cmake ..; make;

